import { Video as VideoBase } from './common';
export * from './common';
export declare class Video extends VideoBase {
    private _player;
    private _playerController;
    private _src;
    private _subtitling;
    private _subtitleLabel;
    private _subtitleLabelContainer;
    private _didPlayToEndTimeObserver;
    private _didPlayToEndTimeActive;
    private _observer;
    private _observerActive;
    private _videoLoaded;
    private _playbackTimeObserver;
    private _playbackTimeObserverActive;
    private _videoPlaying;
    private _videoFinished;
    private enableSubtitles;
    nativeView: any;
    constructor();
    _setNativeVideo(nativeVideoPlayer: any): void;
    updateAsset(nativeVideoAsset: AVAsset): void;
    _setNativePlayerSource(nativePlayerSrc: string): void;
    private _init;
    private _setupSubtitleLabel;
    private _updateSubtitles;
    private AVPlayerItemDidPlayToEndTimeNotification;
    play(): void;
    pause(): void;
    mute(mute: boolean): void;
    seekToTime(seconds: number): void;
    getDuration(): number;
    getCurrentTime(): any;
    setVolume(volume: number): void;
    setPlaybackSpeed(speed: number): void;
    destroy(): void;
    private _addStatusObserver;
    private _removeStatusObserver;
    private _addPlaybackTimeObserver;
    private _removePlaybackTimeObserver;
    private _autoplayCheck;
    private _backgroundAudioCheck;
    playbackReady(): void;
    playbackStart(): void;
}
